name: Windows build (SatisRaporGuncelleme)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install pyinstaller pandas openpyxl numpy holidays plyer
          }

      - name: Build EXE (onefile)
        run: |
          $icon = (Test-Path "icon.png") ? "--icon icon.png" : ""
          pyinstaller --noconfirm --windowed --onefile `
            --name "SatisRaporGuncelleme" `
            $icon `
            satis_rapor_guncelleme.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-exe
          path: dist/SatisRaporGuncelleme.exe

  installer:
    runs-on: windows-latest
    needs: build-windows
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-exe
          path: dist

      # Inno Setup .iss 'dist\SatisRaporGuncelleme\*' bekliyor → exe'yi klasöre taşıyoruz
      - name: Place exe into dist\SatisRaporGuncelleme\
        run: |
          New-Item -ItemType Directory -Force -Path dist\SatisRaporGuncelleme | Out-Null
          Move-Item -Force dist\SatisRaporGuncelleme.exe dist\SatisRaporGuncelleme\

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer (Inno Setup)
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' SatisRaporGuncelleme.iss

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-installer
          path: Output/SatisRaporGuncelleme-Setup.exe
