name: Windows EXE + Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert icon (PNG -> ICO, optional)
        shell: pwsh
        run: |
          if (Test-Path "icon.png") { python convert_icon.py }

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          $iconArg = ""
          if (Test-Path "icon.ico") { $iconArg = "--icon icon.ico" }

          if (Test-Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path dist)  { Remove-Item -Recurse -Force dist }
          if (Test-Path SatisRaporGuncelleme.spec) { Remove-Item -Force SatisRaporGuncelleme.spec }

          pyinstaller --noconfirm --windowed --name "SatisRaporGuncelleme" $iconArg `
            satis_rapor_guncelleme.py

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Build Windows Installer (Inno Setup)
        shell: pwsh
        run: |
          & 'C:/Program Files (x86)/Inno Setup 6/ISCC.exe' 'SatisRaporGuncelleme.iss'

      - name: Upload artifacts (EXE app folder + Installer)
        uses: actions/upload-artifact@v4
        with:
          name: SatisRaporGuncelleme-win
          path: |
            dist/SatisRaporGuncelleme/**
            Output/*.exe
