name: Windows build (SatisRaporGuncelleme)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --windowed `
            --name "SatisRaporGuncelleme" `
            --icon icon.png `
            satis_rapor_guncelleme.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-exe
          path: dist/SatisRaporGuncelleme/**

  installer:
    runs-on: windows-latest
    needs: build-windows
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-exe
          path: dist

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer (Inno Setup)
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' SatisRaporGuncelleme.iss

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: SatisRaporGuncelleme-win-installer
          path: Output/SatisRaporGuncelleme-Setup.exe
